unstable_features = true
array_width = 120
attr_fn_like_width = 120
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
chain_width = 120
wrap_comments = false
empty_item_single_line = true
enum_discrim_align_threshold = 12
fn_call_width = 120
fn_single_line = true
imports_indent = "Visual"
indent_style = "Visual"
max_width = 160
overflow_delimited_expr = true
struct_field_align_threshold = 20
struct_lit_width = 80
struct_variant_width = 80
trailing_comma = "Vertical"
use_field_init_shorthand = true